security_authn_requests_sign: 1
security_messages_sign: 1
strict: 1
_core:
  default_config_hash: xZrT8_AI7UriK8S3VCF6txGozXhDJ4aClCbEaA3-3KE
sp_name_id_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
unique_id_attribute: 'urn:oid:2.5.4.45'
create_users: 1
map_users: 1
sync_name: 1
sync_mail: 1
user_name_attribute: 'urn:oid:2.5.4.41'
user_mail_attribute: 'urn:oid:0.9.2342.19200300.100.1.3'
idp_entity_id: 'https://www.test-creighton.acsitefactory.com/sso/saml2/idp/metadata.php'
sp_entity_id: 'urn:acquia:acsf:saml:sp:creighton:01test:711'
idp_single_sign_on_service: 'https://www.test-creighton.acsitefactory.com/sso/saml2/idp/SSOService.php'
idp_single_log_out_service: 'https://www.test-creighton.acsitefactory.com/sso/saml2/idp/SingleLogoutService.php'